import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game} from './model.js';import {openSave,storageKeys} from './persistence.js';
const key=storageKeys().target,oldKeys=['tsuriiko.game.v3','tsuriiko.game.v3.backup','tsuriiko.game.v3.pre-v4','tsuriiko.game.v4','tsuriiko.core-review.v1','tsuriiko.core-review.v2','kuroshio.prototype.v1'];
const old=Object.fromEntries(oldKeys.map((k,i)=>[k,i%2?'{broken old save':JSON.stringify({money:999999,depthLevel:24})]));
function store(){const data=new Map(Object.entries(old)),access=[];return {data,access,getItem(k){access.push(['get',k]);return data.get(k)??null;},setItem(k,v){access.push(['set',k]);data.set(k,v);}};}
const s=store(),r=openSave(s);assert.equal(r.status,'new');assert.equal(r.game.s.money,0);assert.equal(r.game.s.casts,0);assert.equal(r.game.maxDepth,4);assert.equal(r.game.capacity,3);const g=r.game;g.start();g.cast();for(let i=0;i<10000&&g.s.phase!=='result';i++){g.move(.5+.36*Math.sin(g.s.elapsed*2.2));g.step(1/60);g.drain();}assert.equal(g.s.phase,'result');const reward=g.s.pending.value;assert.ok(g.claim());assert.equal(g.s.money,reward);assert.ok(r.session.write(g.save()));const reload=openSave(s);assert.equal(reload.game.s.money,reward);assert.deepEqual(reload.game.s.book,g.s.book);assert.equal(reload.game.claim(),false);for(const [k,v]of Object.entries(old))assert.equal(s.data.get(k),v);assert.ok(s.access.every(([,k])=>k===key||k===key+'.backup'));
const failures=[];for(const kind of ['corrupt','unknown','read','write','silent-write','orphan']){const x=store();if(kind==='corrupt')x.data.set(key,'{');if(kind==='unknown')x.data.set(key,JSON.stringify({...new Game().s,version:99}));if(kind==='read')x.getItem=()=>{throw Error('denied');};if(kind==='write')x.setItem=()=>{throw Error('quota');};if(kind==='silent-write')x.setItem=()=>{};if(kind==='orphan')x.data.set(key+'.backup','{}');assert.equal(openSave(x).status,'blocked',kind);for(const [k,v]of Object.entries(old))assert.equal(x.data.get(k),v);failures.push(kind);}
const x=store(),active=openSave(x);x.setItem=()=>{throw Error('quota');};active.game.start();assert.equal(active.session.write(active.game.save()),false);assert.ok(active.session.error);failures.push('runtime-write');
const review=store(),rr=openSave(review,'review');assert.equal(rr.status,'new');assert.ok(review.access.every(([,k])=>k.startsWith('tsuriiko.core-release202610.v1')));
fs.mkdirSync('tests/results',{recursive:true});const report={newKey:key,initial:{money:0,casts:0,depth:4,capacity:3},reward,reload:true,legacyKeysNeverReadWrittenOrDeleted:true,failures,reviewIsolated:true};fs.writeFileSync('tests/results/fresh-save.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
