const {chromium}=require(process.env.NODE_REPL_NODE_MODULE_DIRS+'/playwright');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(__dirname,'../../evidence-v03');const money=t=>Number(t.replace(/[^0-9]/g,''));
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,recordVideo:{dir:out,size:{width:390,height:844}}});
 const page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto('http://127.0.0.1:4173');
 assert.equal(await page.evaluate(()=>window.__diagnostics.metrics().audioState),'not-created');await page.screenshot({path:path.join(out,'title.png')});await page.locator('#enter').click();
 let ledger=[];
 // The controller sees elapsed time and visible UI only; no fish coordinates or game state.
 async function cast(n){let wallet=money(await page.locator('#money').innerText());await page.locator('#drop').click();const start=Date.now();await page.mouse.move(195,700);await page.mouse.down();let shot=false;
  while(Date.now()-start<18000){if(await page.locator('#claim').isVisible())break;const t=(Date.now()-start)/1000;await page.mouse.move(195+132*Math.sin(t*1.9),700);if(!shot&&t>2){await page.screenshot({path:path.join(out,`play-${n}.png`)});shot=true;}await page.waitForTimeout(90);}
  await page.mouse.up();await page.locator('#claim').waitFor({state:'visible'});const value=money(await page.locator('#resultMoney').innerText()),title=await page.locator('#resultTitle').innerText(),detail=await page.locator('#resultDetail').innerText();assert.equal(money(await page.locator('#money').innerText()),wallet,'unclaimed reward does not enter wallet');await page.screenshot({path:path.join(out,`result-${n}.png`)});await page.waitForTimeout(700);
  if(n===2){await page.reload();await page.locator('#enter').click();assert.equal(money(await page.locator('#money').innerText()),wallet);assert.equal(money(await page.locator('#resultMoney').innerText()),value);}
  await page.locator('#claim').click();assert.equal(money(await page.locator('#money').innerText()),wallet+value);assert.equal(await page.locator('#drop').isVisible(),true,'one claim leads straight to cast');ledger.push({cast:n,seconds:(Date.now()-start)/1000,value,title,detail});
  if(await page.locator('#upgradeDepth').isEnabled())await page.locator('#upgradeDepth').click();else if(await page.locator('#upgradeCapacity').isVisible()&&await page.locator('#upgradeCapacity').isEnabled())await page.locator('#upgradeCapacity').click();
  console.log('Visible-only cast',n,value,title);await page.waitForTimeout(400);
 }
 for(let n=1;n<=6;n++)await cast(n);
 await page.locator('#bookButton').click();await page.screenshot({path:path.join(out,'book-early.png')});assert.ok((await page.locator('#bookSummary').innerText()).includes('種'));await page.locator('#closeBook').click();
 await page.locator('#pause').click();await page.locator('#volume').press('Home');for(let i=0;i<35;i++)await page.locator('#volume').press('ArrowRight');await page.locator('#motion').check();await page.screenshot({path:path.join(out,'settings.png')});await page.locator('#resume').click();
 await page.locator('#drop').click();await page.waitForTimeout(2100);await page.locator('#pause').click();const paused=await page.evaluate(()=>window.__diagnostics.snapshot());await page.reload();const restored=await page.evaluate(()=>window.__diagnostics.snapshot());assert.equal(paused.depth,restored.depth);await page.locator('#enter').click();await page.locator('#pause').click();const resumed=await page.evaluate(()=>window.__diagnostics.snapshot());assert.equal(paused.money,resumed.money);assert.equal(resumed.volume,.35);assert.equal(resumed.reducedMotion,true);await page.locator('#resume').click();
 await page.locator('#sound').click();assert.equal(await page.evaluate(()=>window.__diagnostics.metrics().audioState),'running');await page.locator('#sound').click();
 const metrics=await page.evaluate(()=>window.__diagnostics.metrics()),video=page.video();await context.close();fs.renameSync(await video.path(),path.join(out,'opening-real-time.webm'));
 // Layout test: explicit simulated safe insets; not a real iPhone.
 const small=await browser.newContext({viewport:{width:320,height:568},isMobile:true,hasTouch:true});const p=await small.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173');await p.evaluate(()=>{document.querySelector('#app').style.setProperty('--safe-top','34px');document.querySelector('#app').style.setProperty('--safe-bottom','21px');});await p.setViewportSize({width:321,height:568});await p.setViewportSize({width:320,height:568});await p.locator('#enter').tap();await p.screenshot({path:path.join(out,'small-safe-aim.png')});const rects=await p.locator('button:visible').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {id:e.id,x:r.x,y:r.y,w:r.width,h:r.height};}));assert.ok(rects.every(r=>r.x>=0&&r.x+r.w<=320.1&&r.y>=34&&r.y+r.h<=547&&r.h>=44));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),320);
 await p.locator('#drop').tap();const session=await small.newCDPSession(p);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:160,y:450}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:235,y:450}]});await p.waitForTimeout(1300);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.screenshot({path:path.join(out,'small-safe-play.png')});await small.close();
 assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith('http://127.0.0.1:4173')));await browser.close();
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({engine:'Chrome headless / Windows; no real iPhone',controller:'Fixed sine sweep based on wall-clock elapsed time; visible UI for actions. Does not access fish state.',ledger,metrics,rects,errors,checks:['pending reward survives reload','claim pays once','claim leads straight to cast','settings persist','checkpoint resume','audio explicit start','320px+simulated safe insets','touch drag','no external requests','no JS errors']},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
