import {Game,species} from '../model.js';import fs from 'node:fs';
const policies={idle:()=>.5,sweep:t=>.5+.34*Math.sin(t*1.9),slowSweep:t=>.5+.27*Math.sin(t*1.2)};
function one(g,policy){g.start();for(let t=0;t<.63;t+=1/60)g.step(1/60);g.cast();let t=0;while(g.s.phase!=='result'&&t<20){g.move(policy(t));g.step(1/60);t+=1/60;}if(g.s.phase!=='result')throw Error('Cast did not finish');const value=g.s.earnings;g.claim();return {seconds:t+3.5,value};}
let opening=[];for(const [name,policy] of Object.entries(policies)){const rows=[];for(let seed=0;seed<30;seed++){let g=new Game();g.s.casts=seed*19;g.s.lastClaimedId=g.s.casts;let first=0,earnings=[];for(let n=1;n<=5;n++){let r=one(g,policy);earnings.push(r.value);if(!first&&g.s.money>=g.cost('depth')){first=n;g.upgrade('depth');}}rows.push({firstUpgradeByCast:first||null,earnings});}opening.push({policy:name,controller:'Uses elapsed time only; never accesses fish positions/types/weights',within3:rows.filter(r=>r.firstUpgradeByCast&&r.firstUpgradeByCast<=3).length,runs:30,meanFirstCast:rows.reduce((n,r)=>n+r.earnings[0],0)/30,rows});}
let checkpoints={};let longRuns=[];for(const [name,policy] of Object.entries(policies)){for(let seed=0;seed<5;seed++){let g=new Game();g.s.casts=seed*19;g.s.lastClaimedId=g.s.casts;let sec=0,casts=0,upgrades=[],unlocks=[],previousBook=0;while(sec<900){const r=one(g,policy);sec+=r.seconds;casts++;const count=g.s.book.filter(x=>x.count).length;if(count>previousBook){unlocks.push({seconds:Math.round(sec),species:g.s.book.map((x,i)=>x.count?species[i].name:null).filter(Boolean)});previousBook=count;}
 // Visible-state purchasing policy: depth first, capacity every third depth level.
 let choice=g.s.depthLevel>0&&g.s.capLevel<Math.min(5,Math.floor(g.s.depthLevel/3))?'capacity':'depth';
 if(name==='sweep'&&seed===0){for(const mark of [300,600,900])if(sec>=mark&&!checkpoints[mark])checkpoints[mark]=g.save();}
 if(g.upgrade(choice)){upgrades.push({seconds:Math.round(sec),kind:choice,depth:g.maxDepth,capacity:g.capacity});sec+=1;}
 }longRuns.push({policy:name,seed,seconds:Math.round(sec),casts,depthLevel:g.s.depthLevel,depth:g.maxDepth,capacity:g.capacity,money:g.s.money,nextUpgradeCost:g.cost('depth'),bookCount:g.s.book.filter(x=>x.count).length,bestWeight:g.s.bestWeight,lastUpgradeAt:upgrades.at(-1)?.seconds,upgrades,unlocks});}}
const out={conditions:{durationSeconds:900,fps:60,decisionTimePerCast:3.5,upgradeDecisionSeconds:1,openingSeeds:30,longRunSeeds:5,notHumanPlaytest:true,noFishStateUsedForControl:true},opening,longRuns};
fs.mkdirSync('../evidence-v03',{recursive:true});fs.writeFileSync('../evidence-v03/checkpoints.json',JSON.stringify(checkpoints));fs.writeFileSync('../evidence-v03/economy-results.json',JSON.stringify(out,null,2));console.log(JSON.stringify({opening:opening.map(({rows,...x})=>x),longRuns:longRuns.map(({upgrades,unlocks,...x})=>x)},null,2));
