import test from 'node:test';import assert from 'node:assert/strict';import {Game,species} from '../model.js';import {createStorage,createMonetizationPort} from '../platform.js';
const advance=(g,n)=>{for(let i=0;i<n*60;i++)g.step(1/60);};
const sample={type:3,weight:20,value:430};
function result(){let g=new Game();g.start();g.cast();g.s.phase='landing';g.s.caught=[3];g.s.caughtDetails=[{...sample}];g.finish();return g;}
test('descent does not catch; return catches only enabled spatial contact',()=>{let g=new Game();g.start();g.cast();g.s.fish=[{id:0,...sample,x:.5,depth:2,speed:0,phase:0,caught:false}];advance(g,.12);assert.equal(g.s.caught.length,0);g.s.phase='up';g.s.depth=2.1;g.step(.01);assert.equal(g.s.caught.length,1);});
test('hard capacity limit and full return completes within one second',()=>{let g=new Game();g.start();g.cast();g.s.phase='up';g.s.depth=15;g.s.fish=Array.from({length:12},(_,id)=>({id,...sample,x:.5,depth:15,speed:0,phase:0,caught:false}));g.step(.01);assert.equal(g.s.caught.length,4);advance(g,1.05);assert.equal(g.s.phase,'landing');});
test('result is pending; exactly one claim pays and updates collection',()=>{let g=result();assert.equal(g.s.money,0);assert.equal(g.s.book[3].count,0);assert.equal(g.s.pending.value,430);assert.equal(g.claim(),true);assert.equal(g.s.money,430);assert.equal(g.s.book[3].count,1);assert.equal(g.claim(),false);assert.equal(g.s.money,430);});
test('reload before and after claim never awards twice',()=>{let g=result();let pending=new Game(g.save());assert.equal(pending.restored,true);assert.equal(pending.s.phase,'result');pending.claim();let paid=new Game(pending.save());assert.equal(paid.claim(),false);assert.equal(paid.s.money,430);assert.equal(paid.s.history.length,1);});
test('zero catch still progresses through visible support payment',()=>{let g=new Game();g.start();g.cast();g.s.phase='landing';g.finish();assert.equal(g.s.pending.support,40);g.claim();assert.equal(g.s.money,40);assert.equal(g.s.totalFish,0);});
test('new species and weight record differ; history is bounded',()=>{let g=result();assert.deepEqual(g.s.newSpecies,[3]);g.claim();g.start();g.cast();g.s.phase='landing';g.s.caught=[3];g.s.caughtDetails=[{...sample,weight:24}];g.finish();assert.deepEqual(g.s.newSpecies,[]);assert.deepEqual(g.s.newRecords,[3]);g.claim();assert.equal(g.s.bestWeight,24);assert.equal(new Game(g.save()).s.book[3].best,24);});
test('upgrade stages do not expose all species with the first purchase',()=>{let g=new Game();g.s.money=100000;g.upgrade('depth');g.start();g.cast();assert.ok(g.s.fish.some(f=>f.type===2));assert.ok(g.s.fish.every(f=>f.type<=2));assert.equal(g.maxDepth,32);assert.equal(g.cost('depth'),440);});
test('depth increases do not inflate empty travel time',()=>{for(const level of [0,20]){let g=new Game();g.s.depthLevel=level;g.start();g.cast();g.s.fish=[];advance(g,11);assert.equal(g.s.phase,'result');}});
test('legacy paid results migrate without replaying earnings',()=>{const g=new Game({version:1,phase:'result',money:1234,depthLevel:2,capLevel:1,casts:8,muted:true});assert.equal(g.s.money,1234);assert.equal(g.s.lastClaimedId,8);assert.equal(g.s.pending,null);assert.equal(g.claim(),false);});
test('invalid saves and forged paid entitlement fail safely',()=>{for(const raw of ['{','null',JSON.stringify({...new Game().s,money:-1}),JSON.stringify({...new Game().s,phase:'result',pending:{}})])assert.equal(new Game(raw).restored,false);let g=new Game();g.s.entitlements={adRemoval:true,source:'fake'};assert.equal(new Game(g.save()).s.entitlements.adRemoval,false);});
test('storage keeps an independent prior snapshot and reports quota failures',()=>{const map=new Map(),api={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)},s=createStorage(api,'test');assert.equal(s.write('one'),true);s.write('two');assert.equal(s.load(),'two');assert.equal(s.backup(),'one');assert.equal(createStorage({getItem(){throw Error();},setItem(){throw Error();}}).write('x'),false);});
test('monetization boundary cannot grant purchase or reward without connection',async()=>{let p=createMonetizationPort();assert.equal((await p.getEntitlement()).adRemoval,false);assert.equal((await p.showRewarded()).rewardGranted,false);assert.equal((await p.restorePurchases()).status,'not_connected');});
