import {Game,species} from './model.js?v=harbor-r2';import {rods,baits,bands,hints,ecology} from './catalog.js?v=harbor-r2';import {drawFish,drawBoat} from './art.js?v=harbor-r2';import {harbor,gear,shopInterior,sea,SCALE,worldY} from './scenes.js?v=harbor-r2';import {RecordedAudio} from './audio-engine.js?v=harbor-r2';import {openStore} from './storage.js?v=harbor-r2';
let buyLockedUntil=0;
const $=s=>document.querySelector(s),canvas=$('#world'),ctx=canvas.getContext('2d',{alpha:false});let storage;try{storage=localStorage;}catch{}const store=openStore(storage);let game=store.game||new Game(),page='home',paused=false,blocked=!!store.error,shopKind='rod',detailType=0,audio=null,last=0,w=390,h=844,dpr=1,clock=0,camera=0,toastUntil=0,drag=false,px=0,saveAt=0,frames=[],lastUI=0,saleCount=0;
function stop(){blocked=true;paused=true;audio?.suspend();$('#storageError').hidden=false;document.querySelectorAll('.page').forEach(e=>e.inert=true);}
for(const event of ['click','pointerdown','pointermove','keydown','input','change'])document.addEventListener(event,e=>{if(blocked&&!e.target.closest?.('#storageError')){e.preventDefault();e.stopImmediatePropagation();}},true);
function save(){if(blocked)return false;if(!store.write(game)){stop();return false;}return true;}
function sound(){if(blocked||paused||document.hidden||game.s.muted)return;if(!audio)audio=new RecordedAudio(game.s.volume);audio.resume(page==='play'?game.s.phase:'ready').catch(()=>{});}
function note(name){if(!game.s.muted&&!blocked&&!paused)audio?.play(name);}
function navigate(next){drag=false;page=next;last=0;document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==next);if(next==='shop')renderShop();if(next==='book')renderBook();if(next==='detail')renderDetail();if(next==='result')renderResult();sync();save();audio?.update(next==='play'?game.s.phase:'ready');}
function currency(n){return '¥'+n.toLocaleString();}
function sync(){const s=game.s;$('#homeGear').textContent=rods[s.rodTier].name+' · '+game.maxDepth+'m / '+game.capacity+'尾\n'+currency(s.money);$('#depart').innerHTML=(s.phase==='ready'?'出船する':s.phase==='result'?'釣果を確認する':'釣りの続きへ')+' <span>→</span>';$('.wallet').textContent=currency(s.money);$('#depthLabel').textContent=Math.round(s.depth)+'m';$('#capacity').textContent='保持 '+s.caught.length+' / '+game.capacity+'尾';const band=bands.find(b=>s.depth<b.to)||bands[3];$('#bandLabel').textContent=band.name;$('#sound').textContent=s.muted?'音 OFF':'音 ON';$('#settingsSound').textContent=s.muted?'音をオンにする':'音をオフにする';$('#volume').value=Math.round(s.volume*100);$('#motion').checked=s.reducedMotion;$('#drop').hidden=s.phase!=='aim';$('#playInstruction').textContent=s.phase==='aim'?'準備ができたら、海へ。':s.phase==='down'?'深い潮へ、仕掛けを落とす':s.phase==='landing'?'船に揚げよう！':s.caught.length>=game.capacity?'満載！ 港へ巻き上げよう':'左右にドラッグして魚に合わせる';$('#playEquipment').textContent=game.maxDepth+'m · '+baits[s.capLevel].name;}
function portrait(el,type,known=true,scale=1){const c=el.getContext('2d'),cw=el.width,ch=el.height;c.clearRect(0,0,cw,ch);drawFish(c,cw*.52,ch*.48,type,clock,Math.min(cw/(species[type].size*2.7),ch/(species[type].size*1.6))*scale,1,known,species,game.s.reducedMotion);}
function renderShop(){const list=shopKind==='rod'?rods:baits,tier=shopKind==='rod'?game.s.rodTier:game.s.capLevel;$('#rodTab').setAttribute('aria-selected',shopKind==='rod');$('#baitTab').setAttribute('aria-selected',shopKind==='bait');$('#shopNote').textContent=shopKind==='rod'?'竿・リール・糸・オモリ込みのセット。':'買い切り・エサの補充込み。追加費用はありません。';$('#products').replaceChildren();for(const [i,item]of [...list.entries()].sort((a,b)=>{const rank=i=>i===tier+1?-2:i===tier?-1:i;return rank(a[0])-rank(b[0]);})){const card=document.createElement('article');card.className='product'+(i<=tier?' owned':'');const top=document.createElement('div');top.className='product-top';const icon=document.createElement('canvas');icon.width=220;icon.height=160;gear(icon.getContext('2d'),220,160,shopKind,i);const text=document.createElement('div'),title=document.createElement('h3'),price=document.createElement('div');title.textContent=item.name;price.className=i<=tier?'owned-label':'price';price.textContent=i===tier?'装備中':i<tier?'購入済み':currency(item.price);text.append(title,price);top.append(icon,text);const effect=document.createElement('p');effect.className='effect';effect.textContent=shopKind==='rod'?`到達深度 ${game.maxDepth}m → ${item.depth}m`:`保持数 ${game.capacity}尾 → ${item.capacity+game.s.legacyCapacityBonus}尾`;if(i<=tier)effect.textContent=shopKind==='rod'?`到達深度 ${item.depth}m`:`保持数 ${item.capacity+game.s.legacyCapacityBonus}尾`;const desc=document.createElement('p');desc.className='description';desc.textContent=item.detail;const targets=document.createElement('p');targets.className='targets';targets.textContent='狙える魚：'+item.fish.join('・');const buy=document.createElement('button');buy.dataset.kind=shopKind;buy.dataset.tier=i;const canShop=['ready','aim'].includes(game.s.phase)&&!game.s.pending;buy.disabled=!canShop||i!==tier+1||game.s.money<item.price;buy.textContent=!canShop?'釣りを終えてから購入':i===tier?'装備済み':i<tier?'購入済み':i>tier+1?'前のセットから順に購入':game.s.money<item.price?`あと ${currency(item.price-game.s.money)}`:'購入して装備する';const kind=shopKind;buy.onclick=()=>{if(blocked||performance.now()<buyLockedUntil)return;const old=game.save();if(!game.purchase(kind,i))return;buyLockedUntil=performance.now()+700;buy.disabled=true;if(!save()){game=new Game(old);return;}sound();note('coin');$('#purchaseMessage').textContent=item.name+'を装備しました';const scroll=$('#products').scrollTop;renderShop();$('#products').scrollTop=scroll;sync();};card.append(top,effect,desc,targets,buy);$('#products').append(card);}shopInterior($('#shopScene').getContext('2d'),780,270);}
function renderBook(){$('#bookCount').textContent=game.s.book.filter(b=>b.count).length+' / 7種';$('#bookGrid').replaceChildren();species.forEach((sp,i)=>{const b=game.s.book[i],button=document.createElement('button');button.className='book-tile';button.dataset.fish=i;const art=document.createElement('canvas');art.width=680;art.height=230;portrait(art,i,!!b.count,.8);const meta=document.createElement('div');meta.className='book-meta';const title=document.createElement('strong'),record=document.createElement('small');title.textContent=b.count?sp.name:'まだ見ぬ一尾';record.textContent=b.count?`${b.count}尾 / 最大 ${b.best.toFixed(1)}kg`:'輪郭をタップしてヒントへ';meta.append(title,record);button.append(art,meta);button.onclick=()=>{detailType=i;navigate('detail');};$('#bookGrid').append(button);});}
function renderDetail(){const b=game.s.book[detailType];$('#fishName').textContent=b.count?species[detailType].name:'まだ見ぬ一尾';$('#fishNumber').textContent='FISH RECORD / '+String(detailType+1).padStart(2,'0');$('#fishRecords').replaceChildren();for(const [label,value]of [['最大重量',b.count?b.best.toFixed(1)+'kg':'—'],['捕獲数',b.count?b.count+'尾':'未発見']]){const div=document.createElement('div'),small=document.createElement('small'),strong=document.createElement('strong');small.textContent=label;strong.textContent=value;div.append(small,strong);$('#fishRecords').append(div);}$('#fishHint').textContent=hints[detailType];$('#fishDescription').textContent=b.count?ecology[detailType]:'';portrait($('#fishPortrait'),detailType,!!b.count);}
function renderResult(){const s=game.s,best=[...s.caughtDetails].sort((a,b)=>b.value-a.value)[0];$('#recordBadge').textContent=s.newSpecies.length?'初めての魚に出会った！':s.newRecords.length?'自己記録を更新！':'今日の釣果';$('#resultName').textContent=best?species[best.type].name:'次の一投に期待しよう';$('#resultStats').textContent=best?best.weight.toFixed(1)+'kg · 合計 '+s.caught.length+'尾':'釣果なし · 支度金40円';$('#resultMoney').textContent='+ '+currency(s.earnings);$('#resultFish').hidden=!best;if(best)portrait($('#resultFish'),best.type,true);}
$('#depart').onclick=()=>{sound();if(game.s.phase==='result')navigate('result');else{if(game.s.phase==='ready')game.start();navigate('play');}};$('#drop').onclick=()=>{sound();if(game.cast()){note('cast');camera=0;save();sync();}};
$('#claim').onclick=()=>{if(blocked)return;const before=game.save();if(!game.claim())return;$('#claim').disabled=true;if(save()){sound();note('coin');navigate('home');}else game=new Game(before);$('#claim').disabled=false;};
$('#openShop').onclick=()=>{sound();$('#purchaseMessage').textContent='';navigate('shop');};$('#openBook').onclick=()=>navigate('book');$('#shopBack').onclick=$('#bookBack').onclick=$('#detailHome').onclick=()=>navigate('home');$('#detailBack').onclick=()=>navigate('book');$('#detailShop').onclick=()=>navigate('shop');$('#rodTab').onclick=()=>{shopKind='rod';renderShop();$('#products').scrollTop=0;};$('#baitTab').onclick=()=>{shopKind='bait';renderShop();$('#products').scrollTop=0;};
function settings(open){paused=open;drag=false;last=0;$('#settings').hidden=!open;if(open)audio?.suspend();else sound();sync();save();}
$('#pause').onclick=$('#homeSettings').onclick=()=>settings(true);$('#resume').onclick=()=>settings(false);$('#toHarbor').onclick=()=>{settings(false);navigate('home');};
function toggle(){game.s.muted=!game.s.muted;if(game.s.muted)audio?.suspend();else sound();sync();save();}$('#sound').onclick=$('#settingsSound').onclick=toggle;$('#volume').oninput=e=>{game.s.volume=Number(e.target.value)/100;audio?.setVolume(game.s.volume);save();};$('#motion').onchange=e=>{game.s.reducedMotion=e.target.checked;save();};
$('#play').addEventListener('pointerdown',e=>{if(paused||blocked||e.target.closest('button')||!['down','up'].includes(game.s.phase))return;drag=true;px=e.clientX;$('#play').setPointerCapture(e.pointerId);sound();});$('#play').addEventListener('pointermove',e=>{if(drag){game.move(game.s.targetX+(e.clientX-px)/w*2.2);px=e.clientX;}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('#play').addEventListener(ev,()=>drag=false);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(paused)settings(false);else if(page==='detail')navigate('book');else if(page==='shop'||page==='book')navigate('home');else settings(true);}});
function background(){drag=false;audio?.suspend();save();if(page==='play')settings(true);last=0;}document.addEventListener('visibilitychange',()=>{if(document.hidden)background();else last=0;});window.addEventListener('pagehide',background);window.addEventListener('nativeAudioInterrupted',background);
function resize(){const r=$('#app').getBoundingClientRect();w=r.width;h=r.height;dpr=Math.min(devicePixelRatio||1,2);$('#app').style.setProperty('--logo-size',(w*.18)+'px');canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}new ResizeObserver(resize).observe($('#app'));
function draw(t,dt){if(page==='home'){harbor(ctx,w,h,t);return;}if(page!=='play')return;const s=game.s,top=parseFloat(getComputedStyle($('#app')).getPropertyValue('--top')||0),surface=250+top,target=['down','up'].includes(s.phase)?Math.max(0,worldY(s.depth)-(h*(.56+.17*Math.exp(-Math.max(0,s.depth-16)/22))-surface)):0;if(s.phase==='up'&&s.caught.length>=game.capacity)camera=target;else camera+=(target-camera)*(1-Math.exp(-dt*12));sea(ctx,w,h,t,camera,surface,top);const y=depth=>surface+worldY(depth)-camera;
 if(y(0)>-80)drawBoat(ctx,{x:w*.5,y:y(0)-7,t,scale:w/390,phase:s.phase,caught:s.caught.length,reduced:s.reducedMotion,alpha:s.phase==='up'?0:s.phase==='down'?Math.max(0,1-s.depth/1.2):1});
 if(['down','up'].includes(s.phase)){for(const f of s.fish){const fy=y(f.depth);if(!f.caught&&fy>top+143&&fy<h-125)drawFish(ctx,f.x*w,fy,f.type,t+f.phase,1.08+.13*Math.exp(-Math.max(0,s.castDepth-12)/30),f.speed>=0?1:-1,true,species,s.reducedMotion);}const full=s.caught.length>=game.capacity,hy=full?Math.max(top+190,y(s.depth)):y(s.depth),hx=s.x*w;if(full&&!s.reducedMotion){ctx.strokeStyle='#d4f4e866';ctx.lineWidth=2;for(let k=0;k<10;k++){const sx=(k*.127+.06)%1*w,sy=top+145+((t*(160+s.returnElapsed*180)+k*81)%(h-top-280));ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx-5,sy+20+s.returnElapsed*14);ctx.stroke();}}ctx.strokeStyle='#efe9c7';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w*.55,y(0)-70);ctx.quadraticCurveTo(hx-12,hy-110,hx,hy);ctx.stroke();ctx.strokeStyle='#ffd15a';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(hx,hy-12);ctx.lineTo(hx,hy+10);ctx.quadraticCurveTo(hx+15,hy+23,hx+15,hy+2);ctx.stroke();for(let i=0;i<s.caught.length;i++)drawFish(ctx,hx+(i%2?23:-23),hy+28+Math.floor(i/2)*28,s.caught[i],t+i,.56,i%2?1:-1,true,species,s.reducedMotion);}
 if(s.phase==='landing'){for(let i=0;i<s.caught.length;i++){const p=Math.max(0,Math.min(1,(s.landing-i*.28)/.62)),xx=s.x*w+(w*.5-32+i*11-s.x*w)*p,yy=y(0)+35-110*Math.sin(p*Math.PI)-40*p;drawFish(ctx,xx,yy,s.caught[i],t,.73,1,true,species,s.reducedMotion);}const n=Math.max(0,Math.min(s.caught.length,Math.floor((s.landing-.62)/.28)+1));if(n>saleCount){saleCount=n;note('coin');}}
}
function events(){for(const e of game.drain()){if(e.type==='catch'){note(e.fish>=3?'bigCatch':'catch');$('#catchToast').textContent=species[e.fish].name+' HIT!';toastUntil=clock+1;save();}if(e.type==='full'){$('#catchToast').textContent=game.capacity+'尾 満載！';toastUntil=clock+1.2;}if(e.type==='land'){note('splash');note('land');saleCount=0;}if(e.type==='result'){save();navigate('result');}}}
function frame(now){const raw=last?(now-last)/1000:0,dt=Math.min(raw,.05);last=now;clock+=dt;if(!paused&&!blocked&&!document.hidden){if(page==='play'){game.step(dt);events();audio?.update(game.s.phase,game.s.returnElapsed/2.4);if(clock-saveAt>1){save();saveAt=clock;}}if(clock>toastUntil)$('#catchToast').textContent='';draw(game.s.reducedMotion?0:clock,dt);if(page==='detail')portrait($('#fishPortrait'),detailType,!!game.s.book[detailType].count);if(now-lastUI>120){sync();lastUI=now;}if(raw>0){frames.push(raw*1000);if(frames.length>600)frames.shift();}}requestAnimationFrame(frame);}
window.__diagnostics={snapshot:()=>JSON.parse(game.save()),metrics:()=>({page,paused,blocked,camera,width:w,height:h,meanFrameMs:frames.reduce((a,b)=>a+b,0)/(frames.length||1)}),audio:()=>audio?.diagnostics()||{state:'not-created'}};
resize();sync();if(blocked)stop();requestAnimationFrame(frame);
